[phases.setup]
nixPkgs = ["nodejs_20", "nodejs_20.pkgs.npm"]

[phases.install]
cmds = ["npm install --production=false"]

[phases.build]
cmds = ["npm run build"]

[start]
cmd = "npx prisma generate && npx prisma migrate deploy && node dist/index.js"
